### ISSUE TITLE
Can't compile .ts file with enum.

### ISSUE THREAD

**Issue by bondom** [tomko-team/typeonly#3]
I have types which use `enum`.  I get next error when trying to generate compiled file:

```
Error: Syntax error at line 6:0, mismatched input 'enum' expecting {<EOF>, 'interface', 'type', 'export', 'import'} Error: Syntax error at line 6:0, mismatched input 'enum' expecting {<EOF>, 'interface', 'type', 'export', 'import'}
    at Object.parseTypeOnlyToAst (/Users/yuriifediv/reseguiden/docker-compose-dev/src/rg-product/js/__browserTests__/node_modules/typeonly/dist/parser/parse-typeonly.js:33:15)
    at Object.astProvider (/Users/yuriifediv/reseguiden/docker-compose-dev/src/rg-product/js/__browserTests__/node_modules/typeonly/dist/rto-factory/ProjectInputOutput.js:38:33)
```

Could it be possible to parse files with `enum`s?

**Comment by paleo** [comment]
Sorry, no, enums are not pure types, but also implementations in TypeScript. Enums won't be a part of TypeOnly.
